### ISSUE TITLE
Other Boards and NBIoT Modules that work with Breakout SDK?

### ISSUE THREAD

**Issue by sirfarmalot** [twilio/Breakout_Arduino_Library#30]
Good Day. Thank you for this lib and NBIot solution.

Are there any other chipsets/modules that are confirmed to function well with this sdk?

How are about the BG96 module or the RAK8213?
http://docs.rakwireless.com/en/Cellular/RAK8213/Hardware%20Specification/RAK8213%20Data%20Sheet.pdf

Thank You.

**Comment by rbeiter** [comment]
Hello @sirfarmalot !

Today our Alfa board with the SARA-N410-02B are the only board and cellular module currently supported, but we are actively investigating adding support for the BG96 module at the moment.

Over time we plan for Breakout to have both board (primarily for access to the serial interface to the cellular module) and cellular module support to be easily pluggable, with a selected number of especially popular modules initially offered.  The interfaces will be publicly extendable and with Breakout being open source we will welcome community involvement in bringing support for even more modules.

Thank you,
Randy

**Comment by OYTIS** [comment]
Hi @sirfarmalot,
this repository is being deprecated. The [new version of Massive SDK](https://github.com/twilio/Breakout_Massive_SDK_Arduino) supports BG96 along with SARA-R4/N4
